version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER="${DB_USER}"
      - POSTGRES_PASSWORD="${DB_PASS}"
      - POSTGRES_DB="${DB_NAME}"  
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_MAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_PASS}"
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres