definitions:
  models.Game:
    properties:
      cover_adr:
        type: string
      genders:
        type: string
      id:
        type: integer
      name:
        type: string
      rating:
        type: number
      reviews:
        type: integer
    type: object
  models.Like:
    properties:
      id:
        type: integer
      review_id:
        type: integer
      user_id:
        type: integer
    type: object
  models.Login:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  models.Review:
    properties:
      game_id:
        type: integer
      grade:
        type: number
      id:
        type: integer
      opinion:
        type: string
      user_id:
        type: integer
    type: object
  models.User:
    properties:
      birth_date:
        type: string
      id:
        type: integer
      mail:
        type: string
      name:
        type: string
      password:
        type: string
      user_name:
        type: string
    type: object
info:
  contact: {}
paths:
  /games:
    get:
      consumes:
      - application/json
      description: Route to show a game
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Game'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
      summary: Show a game
      tags:
      - games
    post:
      consumes:
      - application/json
      description: With params creates a new game
      parameters:
      - description: Game Model
        in: body
        name: game
        required: true
        schema:
          $ref: '#/definitions/models.Game'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Game'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
        "409":
          description: Conflict
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
      summary: Creates a new game
      tags:
      - games
  /healthz:
    get:
      consumes:
      - application/json
      description: Route to health check
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Healthcheck
      tags:
      - health
  /like:
    delete:
      consumes:
      - application/json
      description: Route to delete a like
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
      summary: Show a like
      tags:
      - likes
    post:
      consumes:
      - application/json
      description: With params likes a review
      parameters:
      - description: Like Model
        in: body
        name: like
        required: true
        schema:
          $ref: '#/definitions/models.Like'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Like'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
      summary: Likes a review
      tags:
      - likes
  /likes/review:
    get:
      consumes:
      - application/json
      description: Route to show likes by review
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "404":
          description: Not Found
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
      summary: Show likes by review
      tags:
      - likes
  /likes/user:
    get:
      consumes:
      - application/json
      description: Route to show likes by user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "404":
          description: Not Found
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
      summary: Show likes by user
      tags:
      - likes
  /login:
    post:
      consumes:
      - application/json
      description: With params login
      parameters:
      - description: Login Model
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/models.Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Login'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
        "403":
          description: Forbidden
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
      summary: login
      tags:
      - login
  /readiness:
    get:
      consumes:
      - application/json
      description: Route to readiness check
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Healthcheck
      tags:
      - health
  /review:
    delete:
      consumes:
      - application/json
      description: Route to delete a review
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
      summary: Delete a review
      tags:
      - reviews
    get:
      consumes:
      - application/json
      description: Route to show a review
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Review'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
      summary: Show a review
      tags:
      - reviews
    post:
      consumes:
      - application/json
      description: With params creates a new review
      parameters:
      - description: Review Model
        in: body
        name: review
        required: true
        schema:
          $ref: '#/definitions/models.Review'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Review'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
      summary: Creates a new review
      tags:
      - reviews
  /reviews:
    get:
      consumes:
      - application/json
      description: Route to show last reviews
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Review'
            type: array
        "404":
          description: Not Found
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
      summary: Show last reviews
      tags:
      - reviews
  /reviews/user:
    get:
      consumes:
      - application/json
      description: Route to show last reviews by user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Review'
            type: array
        "404":
          description: Not Found
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
      summary: Show last reviews by user
      tags:
      - reviews
  /users:
    delete:
      consumes:
      - application/json
      description: Route to show an user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
      summary: Show an user
      tags:
      - users
    get:
      consumes:
      - application/json
      description: Route to show an user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
      summary: Show an user
      tags:
      - users
    post:
      consumes:
      - application/json
      description: With params creates a new user
      parameters:
      - description: User Model
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
        "409":
          description: Conflict
          schema:
            additionalProperties:
              items:
                type: string
              type: array
            type: object
      summary: Creates a new user
      tags:
      - users
swagger: "2.0"
